var tfcDoubleIngot = ['Double Ingot']
function capfirst(string) {
    return string[0].toUpperCase() + string.slice(1);
  }
  tfcDoubleIngot.forEach(di => {

onEvent(`item.registry`, event => {
        
event.create(`actinium_225_double_ingot`).displayName(`${di} Actinium 225`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x848FAF)
event.create(`actinium_227_double_ingot`).displayName(`${di} Actinium 227`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x848FAF)
event.create(`actinium_228_double_ingot`).displayName(`${di} Actinium 228`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x848FAF)
event.create(`actinium_double_ingot`).displayName(`${di} Actinium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x848FAF)
event.create(`aluminium_double_ingot`).displayName(`${di} Aluminium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x69A4C4)
event.create(`americium_241_double_ingot`).displayName(`${di} Americium 241`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x18483F)
event.create(`americium_242_double_ingot`).displayName(`${di} Americium 242`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x18483F)
event.create(`americium_244_double_ingot`).displayName(`${di} Americium 244`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x18483F)
event.create(`americium_245_double_ingot`).displayName(`${di} Americium 245`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x18483F)
event.create(`americium_246_double_ingot`).displayName(`${di} Americium 246`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x18483F)
event.create(`americium_double_ingot`).displayName(`${di} Americium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x18483F)
event.create(`annealed_copper_double_ingot`).displayName(`${di} Annealed Copper`).texture(`kubejs:item/metal/double_ingot`).color(0, 0xB9662B)
event.create(`antimony_double_ingot`).displayName(`${di} Antimony`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x9898A6)
event.create(`arsenic_double_ingot`).displayName(`${di} Arsenic`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x3C3C34)
event.create(`astatine_215_double_ingot`).displayName(`${di} Astatine 215`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x070508)
event.create(`astatine_217_double_ingot`).displayName(`${di} Astatine 217`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x070508)
event.create(`astatine_218_double_ingot`).displayName(`${di} Astatine 218`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x070508)
event.create(`astatine_219_double_ingot`).displayName(`${di} Astatine 219`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x070508)
event.create(`astatine_double_ingot`).displayName(`${di} Astatine`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x070508)
event.create(`battery_alloy_double_ingot`).displayName(`${di} Battery Alloy`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x745C77)
event.create(`berkelium_248_double_ingot`).displayName(`${di} Berkelium 248`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x3B1F06)
event.create(`berkelium_249_double_ingot`).displayName(`${di} Berkelium 249`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x3B1F06)
event.create(`berkelium_250_double_ingot`).displayName(`${di} Berkelium 250`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x3B1F06)
event.create(`berkelium_251_double_ingot`).displayName(`${di} Berkelium 251`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x3B1F06)
event.create(`berkelium_double_ingot`).displayName(`${di} Berkelium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x3B1F06)
event.create(`bismuth_211_double_ingot`).displayName(`${di} Bismuth 211`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x284141)
event.create(`bismuth_213_double_ingot`).displayName(`${di} Bismuth 213`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x284141)
event.create(`bismuth_214_double_ingot`).displayName(`${di} Bismuth 214`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x284141)
event.create(`bismuth_215_double_ingot`).displayName(`${di} Bismuth 215`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x284141)
event.create(`bismuth_bronze_double_ingot`).displayName(`${di} Bismuth Bronze`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x293333)
event.create(`black_bronze_double_ingot`).displayName(`${di} Black Bronze`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x201028)
event.create(`black_steel_double_ingot`).displayName(`${di} Black Steel`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x282828)
event.create(`blue_steel_double_ingot`).displayName(`${di} Blue Steel`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x222230)
event.create(`brass_double_ingot`).displayName(`${di} Brass`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x5C4100)
event.create(`bronze_double_ingot`).displayName(`${di} Bronze`).texture(`kubejs:item/metal/double_ingot`).color(0, 0xB35A00)
event.create(`caesium_double_ingot`).displayName(`${di} Caesium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x2D271A)
event.create(`californium_248_double_ingot`).displayName(`${di} Californium 248`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x4C3B00)
event.create(`californium_249_double_ingot`).displayName(`${di} Californium 249`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x4C3B00)
event.create(`californium_250_double_ingot`).displayName(`${di} Californium 250`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x4C3B00)
event.create(`californium_251_double_ingot`).displayName(`${di} Californium 251`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x4C3B00)
event.create(`californium_252_double_ingot`).displayName(`${di} Californium 252`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x4C3B00)
event.create(`californium_253_double_ingot`).displayName(`${di} Californium 253`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x4C3B00)
event.create(`californium_254_double_ingot`).displayName(`${di} Californium 254`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x4C3B00)
event.create(`californium_255_double_ingot`).displayName(`${di} Californium 255`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x4C3B00)
event.create(`californium_double_ingot`).displayName(`${di} Californium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x4C3B00)
event.create(`carbon_double_ingot`).displayName(`${di} Carbon`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x070707)
event.create(`cerium_double_ingot`).displayName(`${di} Cerium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x3E4454)
event.create(`chrome_double_ingot`).displayName(`${di} Chrome`).texture(`kubejs:item/metal/double_ingot`).color(0, 0xA48997)
event.create(`cobalt_brass_double_ingot`).displayName(`${di} Cobalt Brass`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x78786B)
event.create(`cobalt_double_ingot`).displayName(`${di} Cobalt`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x3535A6)
event.create(`cupronickel_double_ingot`).displayName(`${di} Cupronickel`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x986456)
event.create(`curium_242_double_ingot`).displayName(`${di} Curium 242`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x261A18)
event.create(`curium_244_double_ingot`).displayName(`${di} Curium 244`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x261A18)
event.create(`curium_245_double_ingot`).displayName(`${di} Curium 245`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x261A18)
event.create(`curium_246_double_ingot`).displayName(`${di} Curium 246`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x261A18)
event.create(`curium_247_double_ingot`).displayName(`${di} Curium 247`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x261A18)
event.create(`curium_248_double_ingot`).displayName(`${di} Curium 248`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x261A18)
event.create(`curium_249_double_ingot`).displayName(`${di} Curium 249`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x261A18)
event.create(`curium_250_double_ingot`).displayName(`${di} Curium 250`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x261A18)
event.create(`curium_double_ingot`).displayName(`${di} Curium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x261A18)
event.create(`duranium_double_ingot`).displayName(`${di} Duranium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x327474)
event.create(`dysprosium_double_ingot`).displayName(`${di} Dysprosium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x505147)
event.create(`einsteinium_253_double_ingot`).displayName(`${di} Einsteinium 253`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x423300)
event.create(`einsteinium_254_double_ingot`).displayName(`${di} Einsteinium 254`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x423300)
event.create(`einsteinium_255_double_ingot`).displayName(`${di} Einsteinium 255`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x423300)
event.create(`einsteinium_256_double_ingot`).displayName(`${di} Einsteinium 256`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x423300)
event.create(`einsteinium_double_ingot`).displayName(`${di} Einsteinium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x423300)
event.create(`electrum_double_ingot`).displayName(`${di} Electrum`).texture(`kubejs:item/metal/double_ingot`).color(0, 0xBBBB49)
event.create(`enriched_naquadah_double_ingot`).displayName(`${di} Enriched Naquadah`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x1C1816)
event.create(`epoxid_double_ingot`).displayName(`${di} Epoxid`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x865E0D)
event.create(`erbium_double_ingot`).displayName(`${di} Erbium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x4B4A50)
event.create(`europium_double_ingot`).displayName(`${di} Europium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x584D29)
event.create(`fermium_255_double_ingot`).displayName(`${di} Fermium 255`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x321946)
event.create(`fermium_256_double_ingot`).displayName(`${di} Fermium 256`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x321946)
event.create(`fermium_257_double_ingot`).displayName(`${di} Fermium 257`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x321946)
event.create(`fermium_258_double_ingot`).displayName(`${di} Fermium 258`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x321946)
event.create(`fermium_259_double_ingot`).displayName(`${di} Fermium 259`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x321946)
event.create(`fermium_260_double_ingot`).displayName(`${di} Fermium 260`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x321946)
event.create(`fermium_double_ingot`).displayName(`${di} Fermium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x321946)
event.create(`fiber_reinforced_epoxy_resin_double_ingot`).displayName(`${di} Fiber Reinforced Epoxy Resin`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x644D0A)
event.create(`fireclay_double_ingot`).displayName(`${di} Fireclay`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x443F3D)
event.create(`francium_221_double_ingot`).displayName(`${di} Francium 221`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x4B4B4B)
event.create(`francium_223_double_ingot`).displayName(`${di} Francium 223`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x4B4B4B)
event.create(`francium_double_ingot`).displayName(`${di} Francium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x4B4B4B)
event.create(`gadolinium_double_ingot`).displayName(`${di} Gadolinium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x363533)
event.create(`gallium_arsenide_double_ingot`).displayName(`${di} Gallium Arsenide`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x676767)
event.create(`gallium_double_ingot`).displayName(`${di} Gallium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x9797AF)
event.create(`germanium_double_ingot`).displayName(`${di} Germanium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x484231)
event.create(`hafnium_double_ingot`).displayName(`${di} Hafnium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x615A57)
event.create(`holmium_double_ingot`).displayName(`${di} Holmium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x6A6B5D)
event.create(`hsse_double_ingot`).displayName(`${di} Hsse`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x214200)
event.create(`hssg_double_ingot`).displayName(`${di} Hssg`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x636300)
event.create(`hsss_double_ingot`).displayName(`${di} Hsss`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x470023)
event.create(`indium_double_ingot`).displayName(`${di} Indium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x6B6A66)
event.create(`invar_double_ingot`).displayName(`${di} Invar`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x7E7E54)
event.create(`iodine_double_ingot`).displayName(`${di} Iodine`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x5F2756)
event.create(`iridium_double_ingot`).displayName(`${di} Iridium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x5B8080)
event.create(`kanthal_double_ingot`).displayName(`${di} Kanthal`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x7B858E)
event.create(`lanthanum_double_ingot`).displayName(`${di} Lanthanum`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x4B4A3B)
event.create(`lead_double_ingot`).displayName(`${di} Lead`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x583F58)
event.create(`lithium_double_ingot`).displayName(`${di} Lithium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x716F80)
event.create(`lutetium_double_ingot`).displayName(`${di} Lutetium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x8A8C88)
event.create(`magnalium_double_ingot`).displayName(`${di} Magnalium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x7D779F)
event.create(`magnesium_double_ingot`).displayName(`${di} Magnesium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x201000)
event.create(`magnetic_iron_double_ingot`).displayName(`${di} Magnetic Iron`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x7E7E7E)
event.create(`magnetic_neodymium_double_ingot`).displayName(`${di} Magnetic Neodymium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x404040)
event.create(`magnetic_steel_double_ingot`).displayName(`${di} Magnetic Steel`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x474747)
event.create(`manganese_double_ingot`).displayName(`${di} Manganese`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x869379)
event.create(`mendelevium_259_double_ingot`).displayName(`${di} Mendelevium 259`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x8A8C88)
event.create(`mendelevium_260_double_ingot`).displayName(`${di} Mendelevium 260`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x8A8C88)
event.create(`mendelevium_double_ingot`).displayName(`${di} Mendelevium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x8A8C88)
event.create(`molybdenum_double_ingot`).displayName(`${di} Molybdenum`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x7C7C97)
event.create(`naquadah_alloy_double_ingot`).displayName(`${di} Naquadah Alloy`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x1A1A1A)
event.create(`naquadah_double_ingot`).displayName(`${di} Naquadah`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x212121)
event.create(`naquadria_double_ingot`).displayName(`${di} Naquadria`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x141414)
event.create(`neodymium_double_ingot`).displayName(`${di} Neodymium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x464646)
event.create(`neptunium_236_double_ingot`).displayName(`${di} Neptunium 236`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x12243A)
event.create(`neptunium_237_double_ingot`).displayName(`${di} Neptunium 237`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x12243A)
event.create(`neptunium_238_double_ingot`).displayName(`${di} Neptunium 238`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x12243A)
event.create(`neptunium_239_double_ingot`).displayName(`${di} Neptunium 239`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x12243A)
event.create(`neptunium_240_double_ingot`).displayName(`${di} Neptunium 240`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x12243A)
event.create(`neptunium_double_ingot`).displayName(`${di} Neptunium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x12243A)
event.create(`neutronium_double_ingot`).displayName(`${di} Neutronium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x9D9D9D)
event.create(`nichrome_double_ingot`).displayName(`${di} Nichrome`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x8687A1)
event.create(`nickel_zinc_ferrite_double_ingot`).displayName(`${di} Nickel Zinc Ferrite`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x2B2B2B)
event.create(`nickel_double_ingot`).displayName(`${di} Nickel`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x7E7E9E)
event.create(`niobium_titanium_double_ingot`).displayName(`${di} Niobium Titanium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x121219)
event.create(`niobium_double_ingot`).displayName(`${di} Niobium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x171717)
event.create(`osmiridium_double_ingot`).displayName(`${di} Osmiridium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x4848B7)
event.create(`osmium_double_ingot`).displayName(`${di} Osmium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x1C1C8F)
event.create(`palladium_double_ingot`).displayName(`${di} Palladium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x555555)
event.create(`platinum_double_ingot`).displayName(`${di} Platinum`).texture(`kubejs:item/metal/double_ingot`).color(0, 0xB1B18B)
event.create(`plutonium_236_double_ingot`).displayName(`${di} Plutonium 236`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x9D2121)
event.create(`plutonium_238_double_ingot`).displayName(`${di} Plutonium 238`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x9D2121)
event.create(`plutonium_239_double_ingot`).displayName(`${di} Plutonium 239`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x9D2121)
event.create(`plutonium_240_double_ingot`).displayName(`${di} Plutonium 240`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x9D2121)
event.create(`plutonium_241_double_ingot`).displayName(`${di} Plutonium 241`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x9D2121)
event.create(`plutonium_242_double_ingot`).displayName(`${di} Plutonium 242`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x9D2121)
event.create(`plutonium_243_double_ingot`).displayName(`${di} Plutonium 243`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x9D2121)
event.create(`plutonium_244_double_ingot`).displayName(`${di} Plutonium 244`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x9D2121)
event.create(`plutonium_246_double_ingot`).displayName(`${di} Plutonium 246`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x9D2121)
event.create(`plutonium_double_ingot`).displayName(`${di} Plutonium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x9D2121)
event.create(`polonium_211_double_ingot`).displayName(`${di} Polonium 211`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x404428)
event.create(`polonium_213_double_ingot`).displayName(`${di} Polonium 213`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x404428)
event.create(`polonium_214_double_ingot`).displayName(`${di} Polonium 214`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x404428)
event.create(`polonium_215_double_ingot`).displayName(`${di} Polonium 215`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x404428)
event.create(`polonium_216_double_ingot`).displayName(`${di} Polonium 216`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x404428)
event.create(`polonium_218_double_ingot`).displayName(`${di} Polonium 218`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x404428)
event.create(`polonium_double_ingot`).displayName(`${di} Polonium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x404428)
event.create(`polycaprolactam_double_ingot`).displayName(`${di} Polycaprolactam`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x1C1C1C)
event.create(`polyethylene_double_ingot`).displayName(`${di} Polyethylene`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x6F5900)
event.create(`polyphenylene_sulfide_double_ingot`).displayName(`${di} Polyphenylene Sulfide`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x6F5900)
event.create(`polystyrene_double_ingot`).displayName(`${di} Polystyrene`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x5A5651)
event.create(`polytetrafluoroethylene_double_ingot`).displayName(`${di} Polytetrafluoroethylene`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x464646)
event.create(`polyvinyl_chloride_double_ingot`).displayName(`${di} Polyvinyl Chloride`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x919B9B)
event.create(`potassium_double_ingot`).displayName(`${di} Potassium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x747474)
event.create(`praseodymium_double_ingot`).displayName(`${di} Praseodymium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x4E4D41)
event.create(`promethium_double_ingot`).displayName(`${di} Promethium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x2F2623)
event.create(`protactinium_231_double_ingot`).displayName(`${di} Protactinium 231`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x514435)
event.create(`protactinium_232_double_ingot`).displayName(`${di} Protactinium 232`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x514435)
event.create(`protactinium_233_double_ingot`).displayName(`${di} Protactinium 233`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x514435)
event.create(`protactinium_234_double_ingot`).displayName(`${di} Protactinium 234`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x514435)
event.create(`protactinium_double_ingot`).displayName(`${di} Protactinium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x514435)   
event.create(`radium_221_double_ingot`).displayName(`${di} Radium 221`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x795F1E)
event.create(`radium_223_double_ingot`).displayName(`${di} Radium 223`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x795F1E)
event.create(`radium_224_double_ingot`).displayName(`${di} Radium 224`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x795F1E)
event.create(`radium_225_double_ingot`).displayName(`${di} Radium 225`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x795F1E)
event.create(`radium_226_double_ingot`).displayName(`${di} Radium 226`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x795F1E)
event.create(`radium_228_double_ingot`).displayName(`${di} Radium 228`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x795F1E)
event.create(`radium_double_ingot`).displayName(`${di} Radium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x795F1E)
event.create(`red_alloy_double_ingot`).displayName(`${di} Red Alloy`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x8B0000)
event.create(`red_steel_double_ingot`).displayName(`${di} Red Steel`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x5E4343)
event.create(`rhenium_double_ingot`).displayName(`${di} Rhenium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x3C3C3B)
event.create(`rhodium_double_ingot`).displayName(`${di} Rhodium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x94083B)
event.create(`rose_gold_double_ingot`).displayName(`${di} Rose Gold`).texture(`kubejs:item/metal/double_ingot`).color(0, 0xB3A115)
event.create(`rubber_double_ingot`).displayName(`${di} Rubber`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x000000)
event.create(`rubidium_double_ingot`).displayName(`${di} Rubidium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x44413C)
event.create(`ruthenium_double_ingot`).displayName(`${di} Ruthenium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x36748A)
event.create(`samarium_double_ingot`).displayName(`${di} Samarium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0xB0B08D)
event.create(`selenium_double_ingot`).displayName(`${di} Selenium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x6D5583)
event.create(`silicon_double_ingot`).displayName(`${di} Silicon`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x21212C)
event.create(`silicone_double_ingot`).displayName(`${di} Silicone`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x898989)
event.create(`silver_double_ingot`).displayName(`${di} Silver`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x9494AB)
event.create(`soldering_alloy_double_ingot`).displayName(`${di} Soldering Alloy`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x696970)
event.create(`stainless_steel_double_ingot`).displayName(`${di} Stainless Steel`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x868694)
event.create(`steel_double_ingot`).displayName(`${di} Steel`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x555555)
event.create(`sterling_silver_double_ingot`).displayName(`${di} Sterling Silver`).texture(`kubejs:item/metal/double_ingot`).color(0, 0xAF9A9E)
event.create(`strontium_double_ingot`).displayName(`${di} Strontium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x807861)
event.create(`superconductor_double_ingot`).displayName(`${di} Superconductor`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x8D8D8D)
event.create(`tantalum_double_ingot`).displayName(`${di} Tantalum`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x4F4F5D)
event.create(`technetium_double_ingot`).displayName(`${di} Technetium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x6F6D6A)
event.create(`tellurium_double_ingot`).displayName(`${di} Tellurium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x817D87)
event.create(`terbium_double_ingot`).displayName(`${di} Terbium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x5C5D56)
event.create(`thallium_207_double_ingot`).displayName(`${di} Thallium 207`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x7C7C8F)
event.create(`thallium_209_double_ingot`).displayName(`${di} Thallium 209`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x7C7C8F)
event.create(`thallium_210_double_ingot`).displayName(`${di} Thallium 210`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x7C7C8F)
event.create(`thallium_double_ingot`).displayName(`${di} Thallium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x7C7C8F)
event.create(`thorium_227_double_ingot`).displayName(`${di} thorium 227`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x001400)
event.create(`thorium_228_double_ingot`).displayName(`${di} thorium 228`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x001400)
event.create(`thorium_229_double_ingot`).displayName(`${di} thorium 229`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x001400)
event.create(`thorium_230_double_ingot`).displayName(`${di} thorium 230`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x001400)
event.create(`thorium_231_double_ingot`).displayName(`${di} thorium 231`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x001400)
event.create(`thorium_232_double_ingot`).displayName(`${di} thorium 232`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x001400)
event.create(`thorium_233_double_ingot`).displayName(`${di} thorium 233`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x001400)
event.create(`thorium_234_double_ingot`).displayName(`${di} thorium 234`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x001400)
event.create(`thorium_double_ingot`).displayName(`${di} thorium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x001400)
event.create(`thulium_double_ingot`).displayName(`${di} Thulium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x6D6A68)
event.create(`tin_alloy_double_ingot`).displayName(`${di} Tin Alloy`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x787878)
event.create(`tin_double_ingot`).displayName(`${di} Tin`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x898989)
event.create(`titanium_double_ingot`).displayName(`${di} Titanium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x7C5A87)
event.create(`tritanium_double_ingot`).displayName(`${di} Tritanium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x3E0000)
event.create(`tungsten_carbide_double_ingot`).displayName(`${di} Tungsten Carbide`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x200040)
event.create(`tungsten_double_ingot`).displayName(`${di} Tungsten`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x202020)
event.create(`tungstensteel_double_ingot`).displayName(`${di} Tungsten Steel`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x404066)
event.create(`ultimet_double_ingot`).displayName(`${di} Ultimet`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x787899)
event.create(`uranium_232_double_ingot`).displayName(`${di} uranium 232`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x30AC30)
event.create(`uranium_233_double_ingot`).displayName(`${di} uranium 233`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x30AC30)
event.create(`uranium_234_double_ingot`).displayName(`${di} uranium 234`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x30AC30)
event.create(`uranium_235_double_ingot`).displayName(`${di} uranium 235`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x30AC30)
event.create(`uranium_236_double_ingot`).displayName(`${di} uranium 236`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x30AC30)
event.create(`uranium_237_double_ingot`).displayName(`${di} uranium 237`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x30AC30)
event.create(`uranium_238_double_ingot`).displayName(`${di} uranium 238`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x30AC30)
event.create(`uranium_239_double_ingot`).displayName(`${di} uranium 239`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x30AC30)
event.create(`uranium_240_double_ingot`).displayName(`${di} uranium 240`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x30AC30)
event.create(`uranium_double_ingot`).displayName(`${di} uranium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x30AC30)
event.create(`vanadium_gallium_double_ingot`).displayName(`${di} Vanadium Gallium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x575760)
event.create(`vanadium_steel_double_ingot`).displayName(`${di} Vanadium Steel`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x7E7E7E)
event.create(`vanadium_double_ingot`).displayName(`${di} Vanadium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x202020)
event.create(`vibranium_double_ingot`).displayName(`${di} Vibranium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x00ABAB)
event.create(`wrought_iron_double_ingot`).displayName(`${di} Wrought Iron`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x837676)
event.create(`ytterbium_double_ingot`).displayName(`${di} Ytterbium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x573C38)
event.create(`yttrium_barium_cuprate_double_ingot`).displayName(`${di} Yttrium Barium Cuprate`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x342A2E)
event.create(`yttrium_double_ingot`).displayName(`${di} Yttrium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x573C38)
event.create(`zinc_double_ingot`).displayName(`${di} Zinc`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x9A9AA4)
event.create(`zirconium_double_ingot`).displayName(`${di} Zirconium`).texture(`kubejs:item/metal/double_ingot`).color(0, 0x9A9AA4)

    })
})