// priority: 0
var TFCStoneTypes = [``,`basalt`,`chalk`,`chert`,`claystone`,`conglomerate`,`dacite`,`diorite`,`dolomite`,`gabbro`,`gneiss`,`granite`,`limestone`,`marble`,`phyllite`,`quartzite`,`rhyolite`,`schist`,`shale`,`slate`,`venus`,`mars`,`moon``mercury`,`endstone`,`netherrack`]
	
TFCStoneTypes.forEach(stonetype => {
	let displayMaterial = capfirst(`${stonetype}`)

onEvent(`item.registry`, event => {

	event.create(`chunk_${stonetype}_almandine`).displayName(`Chunk ${displayMaterial} Almandine`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xED0000)
    event.create(`chunk_${stonetype}_aluminium`).displayName(`Chunk ${displayMaterial} Aluminium`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x69A4C4)
    event.create(`chunk_${stonetype}_amethyst`).displayName(`Chunk ${displayMaterial} Amethyst`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x7B5DAF)
	event.create(`chunk_${stonetype}_andradite`).displayName(`Chunk ${displayMaterial} Andradite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x6A5500)
	event.create(`chunk_${stonetype}_banded_iron`).displayName(`Chunk ${displayMaterial} Banded Iron`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x845252)
	event.create(`chunk_${stonetype}_barite`).displayName(`Chunk ${displayMaterial} Barite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xBCC0C0)
	event.create(`chunk_${stonetype}_bastnasite`).displayName(`Chunk ${displayMaterial} Bastnasite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x683917)
	event.create(`chunk_${stonetype}_bauxite`).displayName(`Chunk ${displayMaterial} Bauxite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xAC5600)
	event.create(`chunk_${stonetype}_bentonite`).displayName(`Chunk ${displayMaterial} Bentonite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x9C8985)
	event.create(`chunk_${stonetype}_beryllium`).displayName(`Chunk ${displayMaterial} Beryllium`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x5BA45B)
	event.create(`chunk_${stonetype}_bismuth`).displayName(`Chunk ${displayMaterial} Bismuth`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x4F7E7E)
    event.create(`chunk_${stonetype}_sapphire`).displayName(`Chunk ${displayMaterial} Sapphire`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x5D5DBA)
    event.create(`chunk_${stonetype}_blue_topaz`).displayName(`Chunk ${displayMaterial} Blue Topaz`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x3B4869)
	event.create(`chunk_${stonetype}_brown_limonite`).displayName(`Chunk ${displayMaterial} Brown Limonite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xAE5700)
	event.create(`chunk_${stonetype}_calcite`).displayName(`Chunk ${displayMaterial} Calcite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xCDBCB4)
	event.create(`chunk_${stonetype}_cassiterite`).displayName(`Chunk ${displayMaterial} Cassiterite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xBFBFBF)
	event.create(`chunk_${stonetype}_chalcopyrite`).displayName(`Chunk ${displayMaterial} Chalcopyrite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x836221)
	event.create(`chunk_${stonetype}_cinnabar`).displayName(`Chunk ${displayMaterial} Cinnabar`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x8C0000)
	event.create(`chunk_${stonetype}_coal`).displayName(`Chunk ${displayMaterial} Coal`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x414141)
	event.create(`chunk_${stonetype}_cobalt`).displayName(`Chunk ${displayMaterial} Cobalt`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x313199)
	event.create(`chunk_${stonetype}_cobaltite`).displayName(`Chunk ${displayMaterial} Cobaltite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x4545D8)
	event.create(`chunk_${stonetype}_cooperite`).displayName(`Chunk ${displayMaterial} Cooperite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xDEDEAE)
	event.create(`chunk_${stonetype}_copper`).displayName(`Chunk ${displayMaterial} Copper`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x8F3800)
	event.create(`chunk_${stonetype}_diamond`).displayName(`Chunk ${displayMaterial} Diamond`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xBAEDED)
	event.create(`chunk_${stonetype}_emerald`).displayName(`Chunk ${displayMaterial} Emerald`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x4AED4A)
	event.create(`chunk_${stonetype}_galena`).displayName(`Chunk ${displayMaterial} Galena`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x573457)
	event.create(`chunk_${stonetype}_garnierite`).displayName(`Chunk ${displayMaterial} Garnierite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x2DB640)
	event.create(`chunk_${stonetype}_glauconite`).displayName(`Chunk ${displayMaterial} Glauconite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x678F30)
	event.create(`chunk_${stonetype}_gold`).displayName(`Chunk ${displayMaterial} Gold`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xD1BC41)
	event.create(`chunk_${stonetype}_graphite`).displayName(`Chunk ${displayMaterial} Graphite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x676767)
	event.create(`chunk_${stonetype}_green_sapphire`).displayName(`Chunk ${displayMaterial} Green Sapphire`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x5DBA79)
	event.create(`chunk_${stonetype}_grossular`).displayName(`Chunk ${displayMaterial} Grossular`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xBA5D00)
	event.create(`chunk_${stonetype}_ilmenite`).displayName(`Chunk ${displayMaterial} Ilmenite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x3C2F2B)
	event.create(`chunk_${stonetype}_iridium`).displayName(`Chunk ${displayMaterial} Iridium`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xA3A3A6)
    event.create(`chunk_${stonetype}_iron`).displayName(`Chunk ${displayMaterial} Iron`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xB4B4B4)
	event.create(`chunk_${stonetype}_lapis`).displayName(`Chunk ${displayMaterial} Lapis`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x3838B0)
	event.create(`chunk_${stonetype}_lazurite`).displayName(`Chunk ${displayMaterial} Lazurite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x4957C0)
	event.create(`chunk_${stonetype}_lead`).displayName(`Chunk ${displayMaterial} Lead`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x4F384F)
	event.create(`chunk_${stonetype}_lepidolite`).displayName(`Chunk ${displayMaterial} Lepidolite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xB02567)
	event.create(`chunk_${stonetype}_lignite_coal`).displayName(`Chunk ${displayMaterial} Lignite Coal`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x5D4141)
    event.create(`chunk_${stonetype}_lithium`).displayName(`Chunk ${displayMaterial} Lithium`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xA1AABB)
	event.create(`chunk_${stonetype}_magnesite`).displayName(`Chunk ${displayMaterial} Magnesite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xACAC88)
	event.create(`chunk_${stonetype}_magnetite`).displayName(`Chunk ${displayMaterial} Magnetite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x191919)
	event.create(`chunk_${stonetype}_malachite`).displayName(`Chunk ${displayMaterial} Malachite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x678F30)
	event.create(`chunk_${stonetype}_manganese`).displayName(`Chunk ${displayMaterial} Manganese`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xA3A3A6)
    event.create(`chunk_${stonetype}_molybdenite`).displayName(`Chunk ${displayMaterial} Molybdenite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x191919)
	event.create(`chunk_${stonetype}_molybdenum`).displayName(`Chunk ${displayMaterial} Molybdenum`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x65657C)
	event.create(`chunk_${stonetype}_naquadah`).displayName(`Chunk ${displayMaterial} Naquadah`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x2B2B2B)
	event.create(`chunk_${stonetype}_neodymium`).displayName(`Chunk ${displayMaterial} Neodymium`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x383838)
	event.create(`chunk_${stonetype}_nickel`).displayName(`Chunk ${displayMaterial} Nickel`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xA4A4CD)
    event.create(`chunk_${stonetype}_oil_shale`).displayName(`Chunk ${displayMaterial} Oil Shale`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x080808)
    event.create(`chunk_${stonetype}_oilsands`).displayName(`Chunk ${displayMaterial} Oilsands`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x080808)
	event.create(`chunk_${stonetype}_olivine`).displayName(`Chunk ${displayMaterial} Olivine`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x8CED8C)
	event.create(`chunk_${stonetype}_opal`).displayName(`Chunk ${displayMaterial} Opal`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x00007A)
	event.create(`chunk_${stonetype}_osmium`).displayName(`Chunk ${displayMaterial} Osmium`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x2525BD)
    event.create(`chunk_${stonetype}_palladium`).displayName(`Chunk ${displayMaterial} Palladium`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x4B4B4B)
	event.create(`chunk_${stonetype}_pentlandite`).displayName(`Chunk ${displayMaterial} Pentlandite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x7C7104)
    event.create(`chunk_${stonetype}_phosphate`).displayName(`Chunk ${displayMaterial} Phosphate`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xD7D700)
    event.create(`chunk_${stonetype}_phosphorus`).displayName(`Chunk ${displayMaterial} Phosphorus`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xD7D700)
    event.create(`chunk_${stonetype}_pitchblende`).displayName(`Chunk ${displayMaterial} Pitchblende`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xC1CB00)
	event.create(`chunk_${stonetype}_platinum`).displayName(`Chunk ${displayMaterial} Platinum`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xE8E8B6)
	event.create(`chunk_${stonetype}_pyrite`).displayName(`Chunk ${displayMaterial} Pyrite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x735C1F)
	event.create(`chunk_${stonetype}_pyrolusite`).displayName(`Chunk ${displayMaterial} Pyrolusite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x7B7B8B)
	event.create(`chunk_${stonetype}_pyrope`).displayName(`Chunk ${displayMaterial} Pyrope`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x4E2141)
    event.create(`chunk_${stonetype}_quart`).displayName(`Chunk ${displayMaterial} Quartz`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xA3B3A3)
    event.create(`chunk_${stonetype}_quartzite`).displayName(`Chunk ${displayMaterial} Quartzite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xA3B3A3)
	event.create(`chunk_${stonetype}_red_garnet`).displayName(`Chunk ${displayMaterial} Red Garnet`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x602626)
	event.create(`chunk_${stonetype}_redstone`).displayName(`Chunk ${displayMaterial} Redstone`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x500000)
	event.create(`chunk_${stonetype}_rock_salt`).displayName(`Chunk ${displayMaterial} Rock Salt`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xBF9F9F)
	event.create(`chunk_${stonetype}_ruby`).displayName(`Chunk ${displayMaterial} Ruby`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x5B2424)
	event.create(`chunk_${stonetype}_rutile`).displayName(`Chunk ${displayMaterial} Rutile`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xC40C55)
    event.create(`chunk_${stonetype}_salt`).displayName(`Chunk ${displayMaterial} Salt`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xCCCCCC)
	event.create(`chunk_${stonetype}_saltpeter`).displayName(`Chunk ${displayMaterial} Saltpeter`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xB7B7B7)
	event.create(`chunk_${stonetype}_scheelite`).displayName(`Chunk ${displayMaterial} Scheelite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xAE7A11)
	event.create(`chunk_${stonetype}_silver`).displayName(`Chunk ${displayMaterial} Silver`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xA7A7C2)
	event.create(`chunk_${stonetype}_soapstone`).displayName(`Chunk ${displayMaterial} Soapstone`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x4E774E)
	event.create(`chunk_${stonetype}_sodalite`).displayName(`Chunk ${displayMaterial} Sodalite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x1010CC)
	event.create(`chunk_${stonetype}_spessartine`).displayName(`Chunk ${displayMaterial} Spessartine`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x7A3030)
	event.create(`chunk_${stonetype}_sphalerite`).displayName(`Chunk ${displayMaterial} Sphalerite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xD1D1D1)
	event.create(`chunk_${stonetype}_spodumene`).displayName(`Chunk ${displayMaterial} Spodumene`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xB19E9E)
	event.create(`chunk_${stonetype}_stibnite`).displayName(`Chunk ${displayMaterial} Stibnite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x3B3B3B)
	event.create(`chunk_${stonetype}_sulfur`).displayName(`Chunk ${displayMaterial} Sulfur`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xA4A400)
	event.create(`chunk_${stonetype}_talc`).displayName(`Chunk ${displayMaterial} Talc`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x428442)
	event.create(`chunk_${stonetype}_tantalite`).displayName(`Chunk ${displayMaterial} Tantalite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x7E4623)
	event.create(`chunk_${stonetype}_tetrahedrite`).displayName(`Chunk ${displayMaterial} Tetrahedrite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xBA1E00)
	event.create(`chunk_${stonetype}_thorium`).displayName(`Chunk ${displayMaterial} Thorium`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x001900)
	event.create(`chunk_${stonetype}_tin`).displayName(`Chunk ${displayMaterial} Tin`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xC8C8C8)
    event.create(`chunk_${stonetype}_topaz`).displayName(`Chunk ${displayMaterial} Topaz`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x7A3D00)
	event.create(`chunk_${stonetype}_tungstate`).displayName(`Chunk ${displayMaterial} Tungstate`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x2E2A1D)
	event.create(`chunk_${stonetype}_uraninite`).displayName(`Chunk ${displayMaterial} Uraninite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x191919)
    event.create(`chunk_${stonetype}_uranium`).displayName(`Chunk ${displayMaterial} Uranium`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x2EDE2E)
    event.create(`chunk_${stonetype}_uvarovite`).displayName(`Chunk ${displayMaterial} Uvarovite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xA7ECA7)
    event.create(`chunk_${stonetype}_vanadium_magnetite`).displayName(`Chunk ${displayMaterial} Vanadium Magnetite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x1E1E34)
	event.create(`chunk_${stonetype}_wulfenite`).displayName(`Chunk ${displayMaterial} Wulfenite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xC46200)
	event.create(`chunk_${stonetype}_yellow_garnet`).displayName(`Chunk ${displayMaterial} Yellow Garnet`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x838334)
    event.create(`chunk_${stonetype}_zinc`).displayName(`Chunk ${displayMaterial} Zinc`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xB4B4B4)
	event.create(`chunk_${stonetype}_powellite`).displayName(`Chunk ${displayMaterial} Powellite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xDEDE00)
	event.create(`chunk_${stonetype}_nether_quartz`).displayName(`Chunk ${displayMaterial} Nether Quartz`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x807584)
	event.create(`chunk_${stonetype}_monazite`).displayName(`Chunk ${displayMaterial} Monazite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x314531)
	event.create(`chunk_${stonetype}_amber`).displayName(`Chunk ${displayMaterial} amber`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x966900)
    event.create(`chunk_${stonetype}_apatite`).displayName(`Chunk ${displayMaterial} Apatite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xBABAED)
	event.create(`chunk_${stonetype}_jade`).displayName(`Chunk ${displayMaterial} jade`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x5DBA79)
	
    
    // event.create(`chunk_${stonetype}_garnet`).displayName(`Chunk ${displayMaterial} Garnet`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x9F4F00)
	// event.create(`chunk_${stonetype}_granitic`).displayName(`Chunk ${displayMaterial} Granitic`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x1E2D2D)
	// event.create(`chunk_${stonetype}_gypsum`).displayName(`Chunk ${displayMaterial} Gypsum`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xBCBCCD)
	// event.create(`chunk_${stonetype}_kyanite`).displayName(`Chunk ${displayMaterial} Kyanite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x5858C8)
	// event.create(`chunk_${stonetype}_lithium`).displayName(`Chunk ${displayMaterial} Lithium`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xA1AABB)
	// event.create(`chunk_${stonetype}_mica`).displayName(`Chunk ${displayMaterial} Mica`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xA2A2AA)
	// event.create(`chunk_${stonetype}_plutonium`).displayName(`Chunk ${displayMaterial} Plutonium`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xDD2E2E)
	// event.create(`chunk_${stonetype}_pollucite`).displayName(`Chunk ${displayMaterial} Pollucite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x857575)
	// event.create(`chunk_${stonetype}_pyrochlore`).displayName(`Chunk ${displayMaterial} Pyrochlore`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x270F00)
	// event.create(`chunk_${stonetype}_realgar`).displayName(`Chunk ${displayMaterial} Realgar`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x921F21)
    // event.create(`chunk_${stonetype}_tricalcium_phosphate`).displayName(`Chunk ${displayMaterial} tricalcium_phosphate`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xDCDC00)
	// event.create(`chunk_${stonetype}_trona`).displayName(`Chunk ${displayMaterial} Trona`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x7E7E58)
	// event.create(`chunk_${stonetype}_yellow_limonite`).displayName(`Chunk ${displayMaterial} Yellow Limonite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0x818100)
	// event.create(`chunk_${stonetype}_zeolite`).displayName(`Chunk ${displayMaterial} Zeolite`).parentModel(`kubejs:item/chunk/${stonetype}/chunk`).texture(`kubejs:item/raw/${stonetype}/chunk`).color(0, 0xC4BCBC)
	})
})
